package Const

// COULD_BUCCINATOR_YES 做唇颊肌
const COULD_BUCCINATOR_YES = 1

// COULD_BUCCINATOR_NO 不做唇颊肌 2
const COULD_BUCCINATOR_NO = 2

// COULD_BUCCINATOR_DEFAULT 不处理唇颊肌
const COULD_BUCCINATOR_DEFAULT = 0
