package Const

// PERMANENT_ERUPTION_YES 恒牙萌出
const PERMANENT_ERUPTION_YES = 1

// PERMANENT_ERUPTION_NO 恒牙未萌出
const PERMANENT_ERUPTION_NO = 2

// PERMANENT_ERUPTION_DEFAULT 恒牙萌出默认
const PERMANENT_ERUPTION_DEFAULT = 0
